### ISSUE TITLE
MatLab vs Processing

### ISSUE THREAD

**Issue by kmartinphd** [SStaret43/ColorAnimation#1]
Do you have access to the full Image proecessing library of Matlab? Have you taught  every one in the group how to use Matlab and does everyone have access? 

As we said, what you have here is ok but ti is not a project. YOu have bigger plans right ?????

**Comment by trushpatel97** [comment]
Yes, we have bigger plans. We just wanted to have something made. Right now we are working on getting a 3D graph to display for pictures. Then we will do the same for a video. Have it display a 3D graph, every frame. After that we will look into working with cameras we can go two routes: working with Arduino sensors so that someone can use their hand to draw an image, and then we can put that image within our program and run through it. Or we can use Arduino sensors to a real-life video and put that into our program and it can run through it.
